package io.paradaux.business.model;

import io.paradaux.hibernia.framework.models.HiberniaPlayer;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.jetbrains.annotations.Nullable;

import java.time.LocalDateTime;
import java.util.UUID;

@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class FirmPlayer implements HiberniaPlayer {
    private String playerUuid;       // CHAR(36)
    private String currentName;      // VARCHAR(32) — widened for Floodgate Bedrock names (economy-flyway V12)
    private String nameLower;        // generated by DB (LOWER(current_name))
    private LocalDateTime firstSeen; // TIMESTAMP
    private LocalDateTime lastSeen;  // TIMESTAMP

    /**
     * @return the player's UUID, or {@code null} when this instance carries no UUID
     *         (default-constructed) or the stored value is not a valid UUID. The
     *         {@code @Nullable} makes the (intentional, ADT-35) deviation from the
     *         non-null {@link HiberniaPlayer#getUniqueId()} contract visible to
     *         consumers and static analysis (ADT firmplayer-null-uuid-contract-break).
     */
    @Nullable
    @Override
    public UUID getUniqueId() {
        if (playerUuid == null || playerUuid.isBlank()) {
            return null;
        }
        try {
            return UUID.fromString(playerUuid);
        } catch (IllegalArgumentException malformed) {
            // A getter must not throw on a malformed stored value; return null per
            // the documented nullable contract rather than surprising callers.
            return null;
        }
    }
}
