/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AccountAccess {
  accountId: number;
  addedByUuidBin: Buffer;
  createdAt: Generated<Date>;
  level: "AUTHORIZER" | "MEMBER" | "VIEWER";
  removedAt: Generated<Date | null>;
  subjectUuidBin: Buffer;
}

export interface AccountBalances {
  accountId: Generated<number>;
  balance: Generated<Decimal>;
}

export interface AccountBalancesMat {
  accountId: number;
  balance: Generated<Decimal>;
  version: Generated<number>;
}

export interface AccountGroupAccess {
  accountId: number;
  addedByUuidBin: Buffer;
  createdAt: Generated<Date>;
  level: "AUTHORIZER" | "MEMBER" | "VIEWER";
  lpGroup: string;
  removedAt: Generated<Date | null>;
}

export interface AccountReadAccessApi {
  accountId: number;
  subjectUuidBin: Buffer;
}

export interface AccountReadAccessWeb {
  accountId: number;
  subjectUuidBin: Buffer;
}

export interface AccountRedirects {
  accountId: number;
  createdAt: Generated<Date>;
  note: Generated<string | null>;
  redirectUuidBin: Buffer;
}

export interface Accounts {
  _PersonalOwner: Generated<Buffer | null>;
  _SystemPlugin: Generated<string | null>;
  accountId: Generated<number>;
  accountType: "BUSINESS" | "GOVERNMENT" | "PERSONAL" | "SYSTEM";
  allowOverdraft: Generated<number>;
  createdAt: Generated<Date>;
  creditLimit: Generated<Decimal>;
  displayName: Generated<string | null>;
  isArchived: Generated<number>;
  ownerUuidBin: Buffer;
  requiresAuthorization: Generated<number>;
}

export interface ApiKeys {
  accountId: Generated<number | null>;
  expiresAt: Date;
  firmId: Generated<number | null>;
  issuedAt: Generated<Date>;
  /**
   * jti claim — updated on reissue
   */
  jwtId: string;
  keyId: Generated<number>;
  keyType: Generated<"BUSINESS" | "GOVERNMENT" | "PERSONAL" | "SERVICE">;
  ownerUuidBin: Buffer;
  revoked: Generated<number>;
  /**
   * deprecated — no longer persisted (ADT-6); always NULL, slated for removal
   */
  token: Generated<string | null>;
}

export interface ApiRateLimitOverride {
  multiplier: Generated<Decimal>;
  note: Generated<string | null>;
  ownerUuidBin: Buffer;
  updatedAt: Generated<Date>;
  /**
   * explorer admin (player UUID) who last changed it
   */
  updatedByBin: Generated<Buffer | null>;
}

export interface ChestshopPreviewPreference {
  playerUuidBin: Buffer;
  visible: Generated<number>;
}

export interface ChestshopSale {
  customerUuidBin: Buffer;
  direction: "BUY" | "SELL";
  isAdminShop: Generated<number>;
  itemCustom: Generated<number>;
  itemData: Generated<string | null>;
  itemKey: string;
  itemName: string;
  material: string;
  occurredAt: Generated<Date>;
  quantity: number;
  saleId: Generated<number>;
  shopAccountId: Generated<number | null>;
  shopAccountType: Generated<"BUSINESS" | "GOVERNMENT" | "PERSONAL" | "SYSTEM" | null>;
  shopFirmId: Generated<number | null>;
  shopOwnerUuidBin: Generated<Buffer | null>;
  shopStock: Generated<number | null>;
  signX: Generated<number | null>;
  signY: Generated<number | null>;
  signZ: Generated<number | null>;
  taxAmount: Generated<Decimal>;
  totalPrice: Decimal;
  txnId: Generated<number | null>;
  unitPrice: Decimal;
  world: Generated<string | null>;
}

export interface ChestshopShop {
  active: Generated<number>;
  batchQty: number;
  buyPrice: Generated<Decimal | null>;
  createdAt: Generated<Date>;
  currentStock: Generated<number | null>;
  estimatedCapacity: Generated<number | null>;
  hologram: Generated<number>;
  isAdminShop: Generated<number>;
  itemCustom: Generated<number>;
  itemData: Generated<string | null>;
  itemKey: string;
  itemName: string;
  lastSeen: Generated<Date>;
  material: string;
  sellPrice: Generated<Decimal | null>;
  shopAccountId: Generated<number | null>;
  shopAccountType: Generated<"BUSINESS" | "GOVERNMENT" | "PERSONAL" | "SYSTEM" | null>;
  shopFirmId: Generated<number | null>;
  shopId: Generated<number>;
  shopOwnerUuidBin: Generated<Buffer | null>;
  signX: number;
  signY: number;
  signZ: number;
  stockAt: Generated<Date | null>;
  visible: Generated<number>;
  world: string;
  worldUuid: Generated<Buffer | null>;
}

export interface EconomyPlayers {
  currentName: string;
  firstSeen: Generated<Date>;
  lastLoginEpoch: Generated<number | null>;
  lastSeen: Generated<Date>;
  nameLower: Generated<string | null>;
  playerUuidBin: Buffer;
}

export interface ExplorerAudit {
  actorName: Generated<string | null>;
  actorRole: Generated<string | null>;
  actorSub: string;
  actorUuidBin: Generated<Buffer | null>;
  at: Generated<Date>;
  auditId: Generated<number>;
  method: string;
  outcome: number;
  path: string;
  sourceIp: Generated<string | null>;
  targetId: Generated<string | null>;
  targetType: Generated<string | null>;
}

export interface ExplorerGroup {
  createdAt: Generated<Date>;
  createdByUuidBin: Generated<Buffer | null>;
  description: Generated<string | null>;
  groupId: Generated<number>;
  luckpermsNode: Generated<string | null>;
  name: string;
}

export interface ExplorerGroupCapability {
  capability: string;
  groupId: number;
}

export interface ExplorerGroupMember {
  addedAt: Generated<Date>;
  addedByUuidBin: Generated<Buffer | null>;
  groupId: number;
  playerUuidBin: Buffer;
  source: Generated<"luckperms" | "manual">;
}

export interface ExplorerIdentity {
  keycloakSub: string;
  linkedAt: Generated<Date>;
  linkedBy: Generated<string | null>;
  minecraftName: Generated<string | null>;
  playerUuidBin: Buffer;
}

export interface ExplorerLinkCode {
  code: string;
  createdAt: Generated<Date>;
  expiresAt: Date;
  keycloakSub: string;
  minecraftName: Generated<string | null>;
}

export interface ExplorerRole {
  grantedAt: Generated<Date>;
  grantedByUuidBin: Generated<Buffer | null>;
  playerUuidBin: Buffer;
  role: string;
}

export interface Firm {
  createdAt: Generated<Date>;
  defaultAccountId: Generated<number | null>;
  discordUrl: Generated<string | null>;
  displayName: string;
  firmId: Generated<number>;
  hqRegion: Generated<string | null>;
  isArchived: Generated<number>;
  proprietorUuidBin: Buffer;
  updatedAt: Generated<Date>;
}

export interface FirmAccounts {
  accountId: number;
  addedAt: Generated<Date>;
  firmId: number;
  removedAt: Generated<Date | null>;
}

export interface FirmEmployee {
  addedByUuidBin: Generated<Buffer | null>;
  firmId: number;
  isCurrent: Generated<number | null>;
  joinedAt: Generated<Date>;
  leftAt: Generated<Date | null>;
  playerUuidBin: Buffer;
  removedByUuidBin: Generated<Buffer | null>;
  roleId: number;
}

export interface FirmInvites {
  createdAt: Generated<Date>;
  expiresAt: Date;
  firmId: number;
  invitedByUuidBin: Buffer;
  inviteId: Generated<number>;
  pendingOnly: Generated<number | null>;
  playerUuidBin: Buffer;
  status: Generated<"ACCEPTED" | "DENIED" | "EXPIRED" | "PENDING">;
}

export interface FirmProperties {
  deletedAt: Generated<Date | null>;
  firmId: number;
  key: string;
  type: "BIGDECIMAL" | "BOOLEAN" | "INTEGER" | "STRING";
  value: string;
}

export interface FirmRole {
  deletedAt: Generated<Date | null>;
  firmId: number;
  isDefault: Generated<number>;
  isProprietorLike: Generated<number>;
  name: string;
  rankOrder: number;
  roleId: Generated<number>;
}

export interface FirmRolePermission {
  deletedAt: Generated<Date | null>;
  permission: "ADMIN" | "CHESTSHOP" | "DEFAULT" | "FINANCIAL";
  roleId: number;
}

export interface FirmTransferRequests {
  activeOnly: Generated<number | null>;
  actorUuidBin: Generated<Buffer | null>;
  createdAt: Generated<Date>;
  expiresAt: Date;
  firmId: number;
  fromUuidBin: Buffer;
  status: Generated<"ACCEPTED" | "ADMIN_OVERRIDE" | "CANCELLED" | "CONFIRMED" | "EXPIRED" | "PENDING">;
  token: string;
  toUuidBin: Buffer;
  transferId: Generated<number>;
}

export interface FlywaySchemaHistory {
  checksum: Generated<number | null>;
  description: string;
  executionTime: number;
  installedBy: string;
  installedOn: Generated<Date>;
  installedRank: number;
  script: string;
  success: number;
  type: string;
  version: Generated<string | null>;
}

export interface GovernmentFines {
  amount: Decimal;
  debtorAccountId: Generated<number | null>;
  fineId: Generated<number>;
  govAccountId: number;
  issuedAt: Generated<Date>;
  issuedByUuidBin: Buffer;
  playerUuidBin: Generated<Buffer | null>;
  reason: string;
  revoked: Generated<number>;
  revokedAt: Generated<Date | null>;
  revokedByUuidBin: Generated<Buffer | null>;
  revokeTxnId: Generated<number | null>;
  txnId: number;
}

export interface LedgerPostings {
  accountId: number;
  amount: Decimal;
  memo: Generated<string | null>;
  postingId: Generated<number>;
  txnId: number;
}

export interface LedgerTxns {
  authorizerUuidBin: Generated<Buffer | null>;
  clientDedupKey: Generated<Buffer | null>;
  initiatorUuidBin: Buffer;
  message: string;
  pluginSystem: Generated<string | null>;
  settlementTime: Generated<Date>;
  tradeTime: Generated<Date>;
  txnId: Generated<number>;
}

export interface WebhookCursor {
  id: Generated<number>;
  lastDispatchedTxnId: Generated<number>;
  updatedAt: Generated<Date>;
}

export interface WebhookDelivery {
  /**
   * the subscribed account the txn matched (payload scope)
   */
  accountId: number;
  attempts: Generated<number>;
  createdAt: Generated<Date>;
  deliveryId: Generated<number>;
  httpStatus: Generated<number | null>;
  lastError: Generated<string | null>;
  nextAttemptAt: Generated<Date>;
  status: Generated<"DELIVERED" | "FAILED" | "PENDING">;
  subscriptionId: number;
  txnId: number;
  updatedAt: Generated<Date>;
}

export interface WebhookSubscription {
  /**
   * scope for PERSONAL/GOVERNMENT keys
   */
  accountId: Generated<number | null>;
  active: Generated<number>;
  apiKeyId: Generated<number | null>;
  consecutiveFailures: Generated<number>;
  createdAt: Generated<Date>;
  /**
   * set when auto-disabled after repeated delivery failures
   */
  disabledAt: Generated<Date | null>;
  /**
   * scope for BUSINESS keys
   */
  firmId: Generated<number | null>;
  keyType: "BUSINESS" | "GOVERNMENT" | "PERSONAL";
  /**
   * snapshot of the issuing key's owner (api_keys.owner_uuid_bin)
   */
  ownerUuidBin: Buffer;
  /**
   * per-subscription HMAC-SHA256 signing key (hex)
   */
  secret: string;
  subscriptionId: Generated<number>;
  targetUrl: string;
  updatedAt: Generated<Date>;
}

export interface DB {
  accountAccess: AccountAccess;
  accountBalances: AccountBalances;
  accountBalancesMat: AccountBalancesMat;
  accountGroupAccess: AccountGroupAccess;
  accountReadAccessApi: AccountReadAccessApi;
  accountReadAccessWeb: AccountReadAccessWeb;
  accountRedirects: AccountRedirects;
  accounts: Accounts;
  apiKeys: ApiKeys;
  apiRateLimitOverride: ApiRateLimitOverride;
  chestshopPreviewPreference: ChestshopPreviewPreference;
  chestshopSale: ChestshopSale;
  chestshopShop: ChestshopShop;
  economyPlayers: EconomyPlayers;
  explorerAudit: ExplorerAudit;
  explorerGroup: ExplorerGroup;
  explorerGroupCapability: ExplorerGroupCapability;
  explorerGroupMember: ExplorerGroupMember;
  explorerIdentity: ExplorerIdentity;
  explorerLinkCode: ExplorerLinkCode;
  explorerRole: ExplorerRole;
  firm: Firm;
  firmAccounts: FirmAccounts;
  firmEmployee: FirmEmployee;
  firmInvites: FirmInvites;
  firmProperties: FirmProperties;
  firmRole: FirmRole;
  firmRolePermission: FirmRolePermission;
  firmTransferRequests: FirmTransferRequests;
  flywaySchemaHistory: FlywaySchemaHistory;
  governmentFines: GovernmentFines;
  ledgerPostings: LedgerPostings;
  ledgerTxns: LedgerTxns;
  webhookCursor: WebhookCursor;
  webhookDelivery: WebhookDelivery;
  webhookSubscription: WebhookSubscription;
}
